name: 'Codeowners Plus'
description: 'Feature-rich alternative to GitHub Code Owners for monoliths and mono-repos'
author: 'Hans Baker'
branding:
  icon: 'plus-circle'
  color: 'blue'
inputs:
  github-token:
    description: 'Github API token'
    required: true
  pr:
    description: 'Pull request number'
    required: true
  repository:
    description: 'The owner and repository name.  For example `octocat/Hello-World`'
    required: true
    default: '${{ github.repository }}'
  verbose:
    description: 'Print debug info'
    required: false
    default: false
  quiet:
    description: 'Disable PR comments and review requests'
    required: false
    default: false

outputs:
  data:
    description: 'JSON string containing all the codeowners data (success, message, file-owners, file-optional, still-required)'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/multimediallc/codeowners-plus:v1.1.0'
