name: 'Rerun Code Owners'

on:
  pull_request_review:
    types: [submitted, dismissed]

permissions: {}

jobs:
  rerun-codeowners:
    name: 'Rerun Codeowners Plus'
    runs-on: ubuntu-latest
    permissions:
      actions: write
      pull-requests: write
      checks: read
    steps:
      - name: 'Rerun Checks'
        uses: shqear93/rerun-checks@fd4069ad25c810179f1cb7437f5535fdf4a8b0fa  # v3
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          check-names: 'Run Codeowners Plus'
