name: 'Rerun Code Owners'

on:
  pull_request_review:
    types: [submitted]

jobs:
  rerun-codeowners:
    name: 'Rerun Codeowners Plus'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code Repository'
        uses: actions/checkout@v4
      
      - name: 'Rerun Checks'
        uses: shqear93/rerun-checks@57ea3adaf84bddd30ed8dda9f27aab0aba231f11  # @v2
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          check-names: 'Run Codeowners Plus'
